leftnav:
- identifier: b09c0fea-c3f4-74b3-9a00-f8889b90cf48
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: edb04418-5ccb-a20c-f0b0-1b2c7157b9a7
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 79bda868-de07-efa2-e9d5-d6af63b2f496
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: b9e8e50d-c685-cee2-f712-a6a4899b6f74
  name: Lecture Notes
  pageRef: /pages/lecture-notes
  weight: 40
- identifier: adcc5fc6-7ecc-6a7d-ea96-1dd23dea6b53
  name: Projects
  pageRef: /pages/projects
  weight: 50
